# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RazorPayPayment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RazorPayPayment

pod 'razorpay-pod', '~> 1.1.1'
end
